# config-management.yaml

apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  # clusterName is required and must be unique among all managed clusters
  clusterName: g4c-sit-01
  git:
    syncRepo: https://github.com/manuuuel/config-sync-env
    syncBranch: 'main'
    secretType: ssh
    policyDir: "config-root"
